config/routes.rb
Rails.application.routes.draw do

  # Read    I can list tasks
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'task/:id', to: 'tasks#show', as: 'task_show'

  get 'task/:id/edit', to: 'tasks#edit'

  patch 'task/:id', to: 'tasks#update', as: 'task_update'

  delete 'task/:id', to: 'tasks#destroy', as: 'task_delete'

  # Delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task, url:task_update_path do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ol>
<% @tasks.each do |task| %>
<li>
  <% if task.completed %>
  <i class="fas fa-times-circle"></i>
  <% else %>
  <i class="far fa-circle"></i>
  <% end %>


  <%= task.title %></li>
<%= link_to "More details", task_show_path(task) %>
<% end %>
</ol>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>My tasks</h1>

<li><%= @task.completed %> <%= @task.title %></li>

<%= link_to 'Destroy', task_delete_path, method: :delete %>